version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:3000
    volumes:
      - ./frontend:/app

    env_file:
      - ./.env
    networks:
      - mynetwork

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:64834923@db:5432/ExchangeNow
    volumes:
      - ./backend:/app

    env_file:
      - ./.env
    networks:
      - mynetwork

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 64834923
      POSTGRES_DB: ExchangeNow
    ports:
      - "5441:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
